### ISSUE TITLE
Has anyone run this code..looks interesting but have failed to configure..have downgraded from ubuntu 20.04 to 18.04 thinking it would help..but no luck

### ISSUE THREAD

**Issue by Mutekeri** [openremote/or-objectdetection#30]
/home/....../or-objectdetection/YOLO_DETECTION/sort.py:32: NumbaWarning: 
Compilation is falling back to object mode WITH looplifting enabled because Function "iou" failed type inference due to: non-precise type pyobject
During: typing of argument at /home/michael/or-objectdetection/YOLO_DETECTION/sort.py (37)

File "sort.py", line 37:
def iou(bb_test,bb_gt):
    <source elided>
  """
  xx1 = np.maximum(bb_test[0], bb_gt[0])
  ^

  @jit
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/michael/anaconda3/envs/pytorch/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/home/michael/anaconda3/envs/pytorch/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/michael/or-objectdetection/YOLO_DETECTION/tracker.py", line 156, in yoloWorker
    tracked_objects = mot_tracker.update(detections.cpu())
  File "/home/michael/or-objectdetection/YOLO_DETECTION/sort.py", line 208, in update
    matched, unmatched_dets, unmatched_trks = associate_detections_to_trackers(dets,trks)
  File "/home/michael/or-objectdetection/YOLO_DETECTION/sort.py", line 152, in associate_detections_to_trackers
    if(d not in matched_indices[:,0]):
TypeError: tuple indices must be integers or slices, not tuple

**Comment by Code-King** [comment]
The First part of the Code is working   , having issues with the following 
from analyse import *
from models import *
from utils import *
from sort import *

**Comment by LuukEbenau** [comment]
New release of the application is out, which renders this issue obsolete. Application should now work completely dockerized and plug and play given that nvidia-cuda is installed correctly on linux.
